// ─── Types ────────────────────────────────────────────────────────────────────

export type Tone = 'professional' | 'neutral' | 'conversational' | 'casual';

// ─── Detection vocabularies ───────────────────────────────────────────────────

/** Generic, low-information AI filler phrases (multi-word). */
export const GENERIC_PHRASES = [
  'in conclusion',
  'to conclude',
  'in summary',
  'to sum up',
  "it's important to note",
  'it is important to note',
  "it's worth noting",
  'it is worth noting',
  "in today's fast-paced world",
  'in the ever-evolving',
  'in the world of',
  'in the realm of',
  'when it comes to',
  'as we all know',
  'plays a crucial role',
  'plays a vital role',
  'plays an important role',
  'plays a key role',
  'delve into',
  'at the end of the day',
  'in this article',
  'in this blog post',
  'in this guide',
  'by the same token',
  'it goes without saying',
  'needless to say',
  'it is essential to',
  "it's essential to",
  'it is crucial to',
  "it's crucial to",
  'it is imperative to',
  'in order to',
  'in order for',
  'a wide range of',
  'unlock the full potential',
  'game changer',
  'seamless experience',
  'holistic approach',
  'navigate the complex',
  'state-of-the-art',
  'cutting-edge',
  'delve',
  'tapestry',
  'landscape',
  'elevate',
  'leverage',
  'streamline',
  'revolutionize',
] as const;

/** Discourse adverbs — the flavour of text that over-uses them reads as AI. */
export const DISCOURSE_ADVERBS = [
  'additionally',
  'importantly',
  'crucially',
  'significantly',
  'essentially',
  'fundamentally',
  'ultimately',
  'interestingly',
  'notably',
  'particularly',
  'remarkably',
  'undoubtedly',
  'similarly',
  'conversely',
  'moreover',
  'furthermore',
  'consequently',
  'subsequently',
  'meanwhile',
  'hence',
  'therefore',
  'thus',
  'accordingly',
  'surprisingly',
  'unexpectedly',
  'increasingly',
  'inevitably',
  'inherently',
  'necessarily',
  'arguably',
  'theoretically',
  'virtually',
  'literally',
  'seamlessly',
  'effectively',
] as const;

// NOTE: ALL_ADVERBS unused - kept for future expanded adverb detection
// const ALL_ADVERBS = [
//   ...DISCOURSE_ADVERBS,
//   'extremely', ... additional adverbs
// ] as const;

/** Formal connectors that AI overuses at sentence starts. */
export const FORMAL_TRANSITIONS = [
  'furthermore',
  'moreover',
  'additionally',
  'consequently',
  'subsequently',
  'nevertheless',
  'nonetheless',
  'therefore',
  'thus',
  'accordingly',
  'in addition',
  'in conclusion',
  'in summary',
  'meanwhile',
  'prior to',
  'subsequent to',
  'in order to',
] as const;

/** Natural transitions (formal + plain) used to measure variety. */
export const TRANSITION_WORDS = [
  ...FORMAL_TRANSITIONS,
  'and',
  'but',
  'so',
  'then',
  'yet',
  'while',
  'although',
  'though',
  'because',
  'since',
  'despite',
  'however',
  'besides',
  'plus',
  'as a result',
  'even so',
  'for example',
  'for instance',
  'afterward',
  'later',
] as const;

/** Natural human hedging — its absence is an AI tell. */
export const HEDGES = [
  'i think',
  'i believe',
  'in my experience',
  'to be honest',
  'honestly',
  'probably',
  'sort of',
  'kind of',
  'pretty much',
  'seems like',
  'seems to',
  'i guess',
  'i suppose',
  'maybe',
  'perhaps',
  'somewhat',
  'a bit',
  'a little',
  'as far as i know',
  'from my perspective',
  'if you ask me',
  "i'd say",
  'i would say',
  'frankly',
  'to my mind',
] as const;

/** First/second-person markers that signal a human voice. */
export const PERSONAL_MARKERS = [
  /\bi\b/g,
  /\bwe\b/g,
  /\bmy\b/g,
  /\bour\b/g,
  /\bme\b/g,
  /\bus\b/g,
  /\byou\b/g,
  /\byour\b/g,
] as const;

/** Contractions — keyed by the phrase they expand, grouped by register tier. */
export const CONTRACTION_MAP: Record<string, string> = {
  'do not': "don't",
  'does not': "doesn't",
  'did not': "didn't",
  'is not': "isn't",
  'are not': "aren't",
  'was not': "wasn't",
  'were not': "weren't",
  'will not': "won't",
  cannot: "can't",
  'can not': "can't",
  'could not': "couldn't",
  'should not': "shouldn't",
  'would not': "wouldn't",
  'must not': "mustn't",
  'have not': "haven't",
  'has not': "hasn't",
  'had not': "hadn't",
  'it is': "it's",
  'that is': "that's",
  'there is': "there's",
  'we are': "we're",
  'you are': "you're",
  'they are': "they're",
  'I am': "I'm",
  'I have': "I've",
  'we have': "we've",
  'they have': "they've",
  'you have': "you've",
  'let us': "let's",
  'I will': "I'll",
  'we will': "we'll",
  'you will': "you'll",
  'they will': "they'll",
  'it will': "it'll",
  'that will': "that'll",
  'would have': "would've",
  'should have': "should've",
  'could have': "could've",
  'might have': "might've",
} as const;

/** Which contractions each register allows. */
export const TONE_CONTRACTION_PHRASES: Record<Tone, string[]> = {
  professional: ['it is', 'that is', 'do not', 'will not', 'cannot'],
  neutral: [
    'it is',
    'that is',
    'there is',
    'do not',
    'does not',
    'did not',
    'is not',
    'are not',
    'was not',
    'were not',
    'will not',
    'cannot',
    'have not',
    'has not',
    'I am',
    'we are',
    'you are',
    'they are',
    'let us',
  ],
  conversational: Object.keys(CONTRACTION_MAP),
  casual: Object.keys(CONTRACTION_MAP),
};

/** Low-information filler phrases with register-appropriate replacements. */
export const FILLER_REPLACEMENTS: Record<string, readonly [string, string, string, string]> = {
  'it is important to note that': ['Note that', 'Note that', 'Worth noting:', 'Heads up:'],
  "it's important to note that": ['Note that', 'Note that', 'Worth noting:', 'Heads up:'],
  'it is worth noting that': ['Note that', 'Worth noting:', 'Worth noting:', 'By the way,'],
  'in conclusion': ['Finally', 'To sum up', 'To wrap up', 'So, long story short'],
  'to conclude': ['Finally', 'To wrap up', 'Alright', 'Alright,'],
  'in summary': ['In short', 'In short', 'Long story short', 'Long story short'],
  "in today's fast-paced world": ['Today', 'These days', 'These days', 'These days'],
  'in the world of': ['in', 'in', 'in', 'in'],
  'in the realm of': ['in', 'in', 'in', 'in'],
  'when it comes to': ['for', 'for', 'for', 'for'],
  'as we all know': ['Of course', 'You know', 'You know', 'We all know'],
  'plays a crucial role in': ['is key to', 'is key to', 'matters a lot in', 'really matters in'],
  'plays a vital role in': ['is key to', 'is key to', 'matters a lot in', 'matters in'],
  'plays an important role in': ['is important in', 'is key to', 'matters in', 'matters in'],
  'plays a key role in': ['is key to', 'is key to', 'matters in', 'matters in'],
  'delve into': ['dig into', 'dig into', 'dig into', 'dig into'],
  'in this article': ['Here', 'Here', 'Here', 'Here'],
  'in this blog post': ['Here', 'Here', 'Here', 'Here'],
  'in this guide': ['Here', 'Here', 'Here', 'Here'],
  'it goes without saying that': ['Clearly', 'Clearly', 'Obviously', 'Obviously'],
  'needless to say': ['Of course', 'Of course', 'You guessed it', 'You guessed it'],
  'it is essential to': ['You need to', 'You need to', 'You should', 'You gotta'],
  "it's essential to": ['You need to', 'You need to', 'You should', 'You gotta'],
  'it is crucial to': ['You need to', 'You need to', 'You should', 'You should'],
  'in order to': ['to', 'to', 'to', 'to'],
  'in order for': ['for', 'for', 'for', 'for'],
  'a wide range of': ['a range of', 'plenty of', 'plenty of', 'loads of'],
  utilize: ['use', 'use', 'use', 'use'],
  commence: ['start', 'start', 'start', 'start'],
  terminate: ['end', 'end', 'end', 'end'],
  approximately: ['about', 'about', 'about', 'about'],
  facilitate: ['help with', 'help with', 'help with', 'help with'],
  'subsequent to': ['after', 'after', 'after', 'after'],
  'prior to': ['before', 'before', 'before', 'before'],
  aforementioned: ['earlier', 'earlier', 'earlier', 'earlier'],
} as const;

/** Register-appropriate alternatives used to avoid transition repetition. */
export const TRANSITION_VARIETY: Record<string, readonly [string[], string[], string[], string[]]> =
  {
    furthermore: [
      ['moreover', 'additionally', 'in addition'],
      ['also', 'additionally', 'besides'],
      ['also', 'plus', 'and'],
      ['plus', 'and', 'and'],
    ],
    moreover: [
      ['furthermore', 'additionally', 'in addition'],
      ['also', 'besides', 'plus'],
      ['plus', 'and', 'and'],
      ['plus', 'and', 'and'],
    ],
    additionally: [
      ['moreover', 'furthermore', 'also'],
      ['also', 'besides', 'plus'],
      ['plus', 'also', 'and'],
      ['plus', 'and', 'and'],
    ],
    consequently: [
      ['therefore', 'thus', 'as a result'],
      ['as a result', 'so', 'therefore'],
      ['so', 'as a result', 'then'],
      ['so', 'then', 'so'],
    ],
    subsequently: [
      ['later', 'then', 'afterward'],
      ['later', 'then', 'afterward'],
      ['then', 'afterward', 'later'],
      ['then', 'later', 'after'],
    ],
    nevertheless: [
      ['nonetheless', 'however', 'still'],
      ['even so', 'still', 'however'],
      ['still', 'even so', 'but'],
      ['still', 'but', 'even so'],
    ],
    nonetheless: [
      ['nevertheless', 'however', 'still'],
      ['even so', 'still', 'but'],
      ['still', 'but', 'even so'],
      ['still', 'but', 'even so'],
    ],
    therefore: [
      ['thus', 'consequently', 'hence'],
      ['so', 'as a result', 'thus'],
      ['so', 'then', 'as a result'],
      ['so', 'so', 'then'],
    ],
    thus: [
      ['therefore', 'consequently', 'hence'],
      ['so', 'as a result', 'therefore'],
      ['so', 'then', 'so'],
      ['so', 'then', 'so'],
    ],
    accordingly: [
      ['therefore', 'consequently', 'thus'],
      ['so', 'as a result', 'thus'],
      ['so', 'then', 'so'],
      ['so', 'then', 'so'],
    ],
    'in addition': [
      ['moreover', 'furthermore', 'also'],
      ['also', 'besides', 'plus'],
      ['plus', 'also', 'and'],
      ['plus', 'and', 'and'],
    ],
    meanwhile: [
      ['in the meantime', 'at the same time', 'while'],
      ['in the meantime', 'while', 'at the same time'],
      ['while', 'in the meantime', 'so'],
      ['while', 'in the meantime', 'so'],
    ],
    'in conclusion': [
      ['finally', 'to conclude', 'ultimately'],
      ['finally', 'to wrap up', 'in the end'],
      ['to wrap up', 'finally', 'in the end'],
      ['so, long story short', 'to wrap up', 'anyway'],
    ],
  } as const;

/** Sentence-initial discourse adverbs → human conversational openers. */
export const SENTENCE_INITIAL_ADVERBS: Record<string, readonly [string, string]> = {
  additionally: ['Also', 'Plus'],
  moreover: ['Also', 'Plus'],
  furthermore: ['Also', 'And'],
  however: ['That said', 'But'],
  therefore: ['So', 'So'],
  thus: ['So', 'So'],
  consequently: ['So', 'So'],
  nevertheless: ['Even so', 'Still'],
  nonetheless: ['Still', 'Still'],
  importantly: ['Worth noting', 'Worth noting'],
  notably: ['Worth noting', 'Worth noting'],
  interestingly: ['Funny enough', 'Funny enough'],
  ultimately: ['In the end', 'In the end'],
  meanwhile: ['In the meantime', 'In the meantime'],
  surprisingly: ['Believe it or not', 'Believe it or not'],
  'in addition': ['Also', 'Plus'],
} as const;

// ─── Passive-voice helpers ────────────────────────────────────────────────────

export const PASSIVE_RE =
  /\b(was|were|is|are|will be|has been|have been|had been|being|be)\s+[a-z]+(?:ed|en|t)\b/gi;

export const IRREGULAR_PAST: Record<string, string> = {
  written: 'wrote',
  made: 'made',
  built: 'built',
  given: 'gave',
  taken: 'took',
  done: 'did',
  seen: 'saw',
  told: 'told',
  shown: 'showed',
  kept: 'kept',
  held: 'held',
  found: 'found',
  brought: 'brought',
  bought: 'bought',
  sent: 'sent',
  sold: 'sold',
  set: 'set',
  put: 'put',
  run: 'ran',
  begun: 'begun',
  chosen: 'chose',
  spoken: 'spoke',
  broken: 'broke',
  driven: 'drove',
  known: 'knew',
  thrown: 'threw',
  grown: 'grew',
  become: 'became',
  come: 'came',
  fallen: 'fell',
  felt: 'felt',
  forgotten: 'forgot',
  gotten: 'got',
  heard: 'heard',
  left: 'left',
  lost: 'lost',
  met: 'met',
  paid: 'paid',
  read: 'read',
  said: 'said',
};
