#!/usr/bin/env node
/**
 * Planning Integration Tool - Auto-generate estimates for PRs and tasks
 * TS migration of scripts/utilities/planning/planning-integration.ps1
 */

import { runSync, runSyncShell } from '../core/run-command.js';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

interface PlanningConfig {
  enabled: boolean;
  estimateOnPR: boolean;
  estimateOnCommit: boolean;
  defaultModel: string;
  thresholds: {
    complexityAuto: number;
    requireBreakdown: number;
  };
}

const defaultConfig: PlanningConfig = {
  enabled: true,
  estimateOnPR: true,
  estimateOnCommit: false,
  defaultModel: 'claude-3.5-sonnet',
  thresholds: {
    complexityAuto: 3,
    requireBreakdown: 5,
  },
};

function loadConfig(): PlanningConfig {
  const configPath = join(process.cwd(), 'config/planning-integration.json');
  if (existsSync(configPath)) {
    try {
      return { ...defaultConfig, ...JSON.parse(readFileSync(configPath, 'utf-8')) };
    } catch {
      return defaultConfig;
    }
  }
  return defaultConfig;
}

function getGitDiffStats(): { files: number; insertions: number; deletions: number } {
  try {
    const diffStat = runSyncShell('git diff --stat --cached 2>/dev/null || git diff --stat').stdout;
    const lines = diffStat.split('\n');
    const summaryLine = lines.find((l) => l.includes('changed') && l.includes('insertions'));

    if (summaryLine) {
      const filesMatch = summaryLine.match(/(\d+)\s+files?/);
      const insertionsMatch = summaryLine.match(/(\d+)\s+insertions?/);
      const deletionsMatch = summaryLine.match(/(\d+)\s+deletions?/);

      return {
        files: filesMatch ? parseInt(filesMatch[1]) : 0,
        insertions: insertionsMatch ? parseInt(insertionsMatch[1]) : 0,
        deletions: deletionsMatch ? parseInt(deletionsMatch[1]) : 0,
      };
    }
  } catch {
    // Git not available or no diff
  }
  return { files: 0, insertions: 0, deletions: 0 };
}

function getDiffComplexityHint(files: number): number {
  if (files <= 2) return 1;
  if (files <= 5) return 2;
  if (files <= 10) return 3;
  if (files <= 20) return 4;
  return 5;
}

function inferTaskTypeFromBranch(): string {
  try {
    const branch = runSync('git', ['branch', '--show-current']).stdout.trim();
    if (branch.startsWith('feature/') || branch.startsWith('feat/')) return 'feature';
    if (branch.startsWith('bugfix/') || branch.startsWith('fix/')) return 'bugfix';
    if (branch.startsWith('refactor/')) return 'refactor';
    if (branch.startsWith('docs/') || branch.startsWith('doc/')) return 'documentation';
    if (branch.startsWith('test/')) return 'test';
    if (branch.startsWith('perf/') || branch.startsWith('performance/')) return 'performance';
    if (branch.startsWith('security/')) return 'security';
  } catch {
    // Git not available
  }
  return 'feature';
}

function generatePRDescription(): string {
  const config = loadConfig();
  if (!config.enabled) return '';

  const stats = getGitDiffStats();
  const complexity = getDiffComplexityHint(stats.files);
  const taskType = inferTaskTypeFromBranch();

  const lines = [
    '## Planning Estimate',
    '',
    `**Task Type:** ${taskType}`,
    `**Estimated Complexity:** ${complexity}/5`,
    `**Files Changed:** ${stats.files}`,
    `**Lines Changed:** +${stats.insertions}/-${stats.deletions}`,
    '',
    '<!-- Generated by planning-integration -->',
    '',
    '## Checklist',
    '',
    '- [ ] Tests added/updated',
    '- [ ] Documentation updated',
    '- [ ] Security review (if applicable)',
    '- [ ] Breaking changes documented',
  ];

  return lines.join('\n');
}

function generateCommitMessage(): string {
  const config = loadConfig();
  if (!config.enabled || !config.estimateOnCommit) return '';

  const stats = getGitDiffStats();
  const complexity = getDiffComplexityHint(stats.files);

  if (stats.files === 0) return '';

  return `[complexity:${complexity}] [files:${stats.files}]`;
}

function main(): void {
  const args = process.argv.slice(2);
  const command = args[0];

  switch (command) {
    case 'pr-description':
      console.log(generatePRDescription());
      break;
    case 'commit-msg':
      console.log(generateCommitMessage());
      break;
    case 'check': {
      const stats = getGitDiffStats();
      const config = loadConfig();
      console.log(JSON.stringify({ stats, config }, null, 2));
      break;
    }
    default:
      console.log(
        'Usage: npx tsx src/planning/planning-integration.ts [pr-description|commit-msg|check]',
      );
      process.exit(1);
  }
}

main();
