#!/usr/bin/env node
/**
 * Skills Index Generator — F4.3
 *
 * Scans the canonical `skills/` directory and the legacy `.opencode/skills/` directory and
 * regenerates `skills/INDEX.md`: one table row per skill with name, directory (source), origin
 * (from frontmatter metadata), deprecation status, and frontmatter description.
 *
 * Canonical directory: `skills/` (declared migration home, AGNOSTIC-USAGE.md). `.opencode/skills/`
 * skills that were duplicated were converted to DEPRECATED stubs pointing at the canonical copy;
 * this generator flags them as `stub-deprecated`.
 *
 * Usage:
 *   npx tsx src/skills-index-generator.ts            # write skills/INDEX.md
 *   npx tsx src/skills-index-generator.ts --dry      # print to stdout, do not write
 *   npx tsx src/skills-index-generator.ts --canonical # only skills/ (skip .opencode/skills/)
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { pathToFileURL } from 'url';

const ROOT = process.cwd();
const CANON_DIR = 'skills';
const LEGACY_DIR = join('.opencode', 'skills');
const OUTPUT = join('skills', 'INDEX.md');

interface SkillRow {
  name: string;
  dir: string;
  status: 'active' | 'stub-deprecated';
  origin: string;
  description: string;
}

interface Frontmatter {
  name?: string;
  description?: string;
  license?: string;
  version?: string;
  metadata?: Record<string, unknown>;
}

/** Parse the YAML frontmatter block (simple line-based parser, handles folded scalars). */
function parseFrontmatter(content: string): Frontmatter {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n/);
  if (!match) return {};
  const lines = match[1].split('\n');
  const fm: Frontmatter = {};
  let currentKey = '';
  let buffer = '';

  const flush = (): void => {
    if (!currentKey) return;
    const existing = (fm as Record<string, unknown>)[currentKey];
    if (currentKey === 'metadata' || typeof existing === 'object') {
      buffer = '';
      return; // nested map already captured, do not overwrite with scalar
    }
    const value = buffer.trim().replace(/^>\s*/, '').replace(/^'(.*)'$/s, '$1').trim();
    (fm as Record<string, unknown>)[currentKey] = value.replace(/\s+/g, ' ');
    buffer = '';
  };

  for (const line of lines) {
    const keyMatch = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (keyMatch && !line.startsWith(' ')) {
      flush();
      currentKey = keyMatch[1];
      if (currentKey === 'metadata') {
        fm.metadata = {};
        buffer = '';
      } else {
        buffer = keyMatch[2];
      }
    } else if (currentKey === 'metadata') {
      // metadata is nested — captured as a raw map
      const nested = line.match(/^\s+([a-zA-Z0-9_-]+):\s*(.*)$/);
      if (nested && fm.metadata && typeof fm.metadata === 'object') {
        fm.metadata[nested[1]] = nested[2].replace(/^['"]|['"]$/g, '');
      }
    } else if (currentKey && (line.startsWith(' ') || line.trim() === '')) {
      if (line.trim() !== '') buffer += ' ' + line.trim();
    }
  }
  flush();
  return fm;
}

function scanDir(baseDir: string, label: string): SkillRow[] {
  const dir = join(ROOT, baseDir);
  if (!existsSync(dir)) return [];
  const rows: SkillRow[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (!entry.isDirectory()) continue;
    const skillPath = join(dir, entry.name, 'SKILL.md');
    if (!existsSync(skillPath)) continue;
    const fm = parseFrontmatter(readFileSync(skillPath, 'utf-8'));
    const description = fm.description ?? '';
    const isStub = /^DEPRECATED/i.test(description);
    const meta = fm.metadata ?? {};
    const originParts: string[] = [];
    if (typeof meta.source === 'string' && meta.source) originParts.push(String(meta.source));
    if (typeof meta.origin === 'string' && meta.origin) originParts.push(String(meta.origin));
    if (fm.license) originParts.push(String(fm.license));
    rows.push({
      name: fm.name && fm.name !== 'SKILL.md' ? fm.name : entry.name,
      dir: label,
      status: isStub ? 'stub-deprecated' : 'active',
      origin: originParts.join(' · ') || 'native',
      description,
    });
  }
  return rows;
}

function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function render(rows: SkillRow[]): string {
  const canon = rows.filter((r) => r.dir === CANON_DIR);
  const stubs = rows.filter((r) => r.status === 'stub-deprecated');
  const active = rows.filter((r) => r.status === 'active');
  const genDate = new Date().toISOString().slice(0, 10);

  const lines: string[] = [];
  lines.push('# Skills Index');
  lines.push('');
  lines.push(
    `> GENERATED by \`src/skills-index-generator.ts\` on ${genDate} — do not edit by hand; regenerate instead.`,
  );
  lines.push('>');
  lines.push('> Canonical directory: **`skills/`** (declared migration home, `AGNOSTIC-USAGE.md`).');
  lines.push(
    '> `.opencode/skills/` is the legacy opencode location: duplicates were merged into `skills/` and',
  );
  lines.push(
    '> replaced with DEPRECATED stubs that redirect to the canonical path. Stubs never delete files;',
  );
  lines.push('> non-SKILL.md assets (references/, scripts/) remain in place.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric                          | Count |');
  lines.push('| ------------------------------- | ----- |');
  lines.push(`| Active in \`skills/\` (canonical) | ${canon.filter((r) => r.status === 'active').length} |`);
  lines.push(
    `| Active in \`.opencode/skills/\` (legacy, not duplicated) | ${rows.filter((r) => r.dir === '.opencode/skills' && r.status === 'active').length} |`,
  );
  lines.push(`| Stub-deprecated (legacy dir)    | ${stubs.length} |`);
  lines.push(`| Total rows                      | ${rows.length} |`);
  lines.push('');
  lines.push('## All Skills');
  lines.push('');
  lines.push('| Skill | Directory | Status | Origin | Description |');
  lines.push('| ----- | --------- | ------ | ------ | ----------- |');
  for (const r of rows) {
    lines.push(
      `| \`${cell(r.name)}\` | \`${r.dir}\` | ${r.status === 'stub-deprecated' ? '⚠️ stub-deprecated' : 'active'} | ${cell(r.origin)} | ${cell(r.description)} |`,
    );
  }
  lines.push('');
  lines.push('<!-- stats -->');
  lines.push(`<!-- active: ${active.length} | stub-deprecated: ${stubs.length} | total: ${rows.length} -->`);
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const args = process.argv.slice(2);
  const dry = args.includes('--dry');
  const canonicalOnly = args.includes('--canonical');

  const rows: SkillRow[] = [
    ...scanDir(CANON_DIR, CANON_DIR),
    ...(canonicalOnly ? [] : scanDir(LEGACY_DIR, '.opencode/skills')),
  ];

  if (rows.length === 0) {
    console.error('[ERROR] No skills found — run from the repository root.');
    process.exit(1);
  }

  const out = render(rows);
  if (dry) {
    console.log(out);
  } else {
    writeFileSync(join(ROOT, OUTPUT), out, 'utf-8');
    const active = rows.filter((r) => r.status === 'active').length;
    const stubs = rows.length - active;
    console.log(
      `[OK] ${OUTPUT} written — ${rows.length} rows (${active} active, ${stubs} stub-deprecated)`,
    );
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
